# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.9

# Fabric API
fabric_version=0.114.3+1.21.4

# Library Properties
jna_version=5.12.1

# Mod Properties
mod_version=4.0
build_game_version=1.21-1.21.1
maven_group=eu.e4b4
archives_base_name=stream-emotes
